### ISSUE TITLE
Supports user friendly input names

### ISSUE THREAD

**Issue by ashis07** [bllim/laravel-to-jquery-validation#4]
"Supports user friendly input names".

I want to replace the field name and add custom message ?

How to make use of it?

**Comment by marcushouse** [comment]
Would be handy if the errors used the label content rather then the field name / ID by default.
e.g. "The last_name field is required." should use the field label "Last Name" instead of the name "last_name"

 Also having ability to set a completely custom message for each validation item would be great. How do we do that?

**Comment by ashis07** [comment]
Yes, lately i figured it out. The approach was to edit app/lang/en/validation.php. 

Anyways, Thanks.
